"""Explicit parametric families whose adjacency tensors are GPU-native.

Each builder returns (adj: uint8[N,N], meta: dict). Adjacency is always
undirected, loopless, and generated by a closed-form or poly-time rule.
"""

from __future__ import annotations

from typing import Callable

import numpy as np

from . import backend
from .bits import bitwise_count


def is_prime(n: int) -> bool:
    if n < 2:
        return False
    if n < 4:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True


def primes_between(lo: int, hi: int) -> list[int]:
    return [p for p in range(lo, hi + 1) if is_prime(p)]


def primitive_root(p: int) -> int:
    """Smallest primitive root modulo prime p."""
    phi = p - 1
    factors: list[int] = []
    n = phi
    d = 2
    while d * d <= n:
        if n % d == 0:
            factors.append(d)
            while n % d == 0:
                n //= d
        d += 1 if d == 2 else 2
    if n > 1:
        factors.append(n)
    for g in range(2, p):
        if all(pow(g, phi // f, p) != 1 for f in factors):
            return g
    raise ValueError(f"no primitive root for {p}")


def _symmetrize(adj: np.ndarray) -> np.ndarray:
    adj = np.asarray(adj, dtype=np.uint8)
    adj = np.maximum(adj, adj.T)
    np.fill_diagonal(adj, 0)
    return adj


def _modpow_matrix(base: np.ndarray, exp: int, mod: int) -> np.ndarray:
    """Batched modular exponentiation — a GPU kernel (square-and-multiply)."""
    result = np.ones_like(base, dtype=np.int64)
    b = np.mod(base.astype(np.int64), mod)
    e = exp
    while e:
        if e & 1:
            result = (result * b) % mod
        b = (b * b) % mod
        e >>= 1
    return result


def paley_prime(p: int) -> tuple[np.ndarray, dict]:
    """Classical Paley: vertices F_p, edge iff x-y is a quadratic residue.

    O(p) connection row via x ↦ x² (not Euler a^{(p-1)/2} on the N×N tensor),
    then a circulant broadcast. Spectrum is closed-form: skip eigendecomposition.
    Run001 DID this for primes p ≡ 1 (mod 4), but via CPU Euler sketches.
    """
    if not is_prime(p) or p % 4 != 1:
        raise ValueError("Paley requires prime p ≡ 1 (mod 4)")
    from .kernels.sieve import quadratic_residue_row

    row = quadratic_residue_row(p)
    adj = np.stack([np.roll(row, i) for i in range(p)]).astype(np.uint8)
    np.fill_diagonal(adj, 0)
    return adj, {
        "construction_type": "paley_prime",
        "gpu_kernel": "O(p) squares + circulant_roll",
        "field": f"F_{p}",
        "params": {"p": p},
        "run001": "done",
        "row": row,
    }


def _nonsquare(p: int) -> int:
    for n in range(2, p):
        if pow(n, (p - 1) // 2, p) == p - 1:
            return n
    raise ValueError("no nonsquare")


def _fq2_mul(
    a: np.ndarray, b: np.ndarray, c: np.ndarray, d: np.ndarray, p: int, nres: int
) -> tuple[np.ndarray, np.ndarray]:
    """(a+b√n)(c+d√n) over F_p."""
    re = (a * c + nres * b * d) % p
    im = (a * d + b * c) % p
    return re, im


def paley_prime_power(p: int, n: int = 2) -> tuple[np.ndarray, dict]:
    """Paley graph of F_{p^n}, n>1, q = p^n ≡ 1 (mod 4).
    GPU kernel: batched F_{p^2} multiply-exponentiate on the outer-difference tensor.
    Run001 DID NOT do this — Paley was restricted to primes.
    """
    if n != 2:
        raise ValueError("this kernel implements F_{p^2} only")
    q = p * p
    if q % 4 != 1:
        raise ValueError("need q ≡ 1 (mod 4)")
    nres = _nonsquare(p)
    # encode field element i as (i % p) + (i // p)*√nres
    ids = np.arange(q, dtype=np.int64)
    re = ids % p
    im = ids // p
    d_re = (re[:, None] - re[None, :]) % p
    d_im = (im[:, None] - im[None, :]) % p
    exp = (q - 1) // 2
    r_re = np.ones((q, q), dtype=np.int64)
    r_im = np.zeros((q, q), dtype=np.int64)
    b_re, b_im = d_re.copy(), d_im.copy()
    e = exp
    while e:
        if e & 1:
            r_re, r_im = _fq2_mul(r_re, r_im, b_re, b_im, p, nres)
        b_re, b_im = _fq2_mul(b_re, b_im, b_re, b_im, p, nres)
        e >>= 1
    # squares map to (1,0); 0 maps to (0,0)
    adj = ((r_re == 1) & (r_im == 0)).astype(np.uint8)
    np.fill_diagonal(adj, 0)
    return adj, {
        "construction_type": "paley_prime_power",
        "gpu_kernel": "F_p2_batch_pow on outer_diff",
        "field": f"F_{q}",
        "params": {"p": p, "n": n, "q": q, "nres": nres},
        "run001": "not_done",
    }


def generalized_paley(p: int, k: int) -> tuple[np.ndarray, dict]:
    """k-th power Paley: edge iff x-y is a k-th power in F_p.
    Requires k | (p-1) and p ≡ 1 (mod 2k) so -1 is a k-th power (undirected).
    GPU kernel: outer_diff + a^{(p-1)/k} == 1.
    Run001 DID NOT do k>2 (only quadratic Paley).
    """
    if not is_prime(p):
        raise ValueError("prime p required")
    if (p - 1) % k != 0:
        raise ValueError("k must divide p-1")
    if (p - 1) // k % 2 != 0:
        raise ValueError("p ≡ 1 (mod 2k) required for undirected GP")
    idx = np.arange(p, dtype=np.int64)
    diff = (idx[:, None] - idx[None, :]) % p
    pows = _modpow_matrix(diff, (p - 1) // k, p)
    adj = (pows == 1).astype(np.uint8)
    np.fill_diagonal(adj, 0)
    return adj, {
        "construction_type": "generalized_paley",
        "gpu_kernel": "outer_diff + kth_power_residue",
        "field": f"F_{p}",
        "params": {"p": p, "k": k},
        "run001": "not_done",
    }


def cyclotomic_union(p: int, e: int, class_mask: int) -> tuple[np.ndarray, dict]:
    """Cayley graph on F_p with connection set a union of cyclotomic classes of index e.

    O(p) geometric-progression fill of each class (not O(p²) dlog tensor), then
    circulant broadcast. Negation-closed masks: 2^{e/2} candidates, Gray-code order.
    """
    if not is_prime(p) or (p - 1) % e != 0:
        raise ValueError("e must divide p-1")
    from .kernels.sieve import cyclotomic_row

    row, class_mask = cyclotomic_row(p, e, class_mask)
    g = primitive_root(p)
    selected = [(i, bool(class_mask & (1 << i))) for i in range(e)]
    adj = np.stack([np.roll(row, i) for i in range(p)]).astype(np.uint8)
    np.fill_diagonal(adj, 0)
    return adj, {
        "construction_type": "cyclotomic_union",
        "gpu_kernel": "O(p) cyclotomic orbits + circulant_roll",
        "field": f"F_{p}",
        "params": {"p": p, "e": e, "mask": int(class_mask), "primitive_root": g,
                   "selected": selected},
        "run001": "not_done",
        "row": row,
    }


def quadratic_form_f2(n_bits: int, form: str = "symplectic") -> tuple[np.ndarray, dict]:
    """Cayley graph on (F_2^n, XOR) with connection set {x : Q(x)=1}.
    GPU kernel: XOR outer product + bitwise quadratic form (popcount / AND).
    Run001 DID NOT use F_2^n quadratic / bent Cayley graphs.
    """
    n = 1 << n_bits
    x = np.arange(n, dtype=np.uint64)
    xor = x[:, None] ^ x[None, :]
    if form == "symplectic":
        q = np.zeros((n, n), dtype=np.uint8)
        for i in range(0, n_bits - 1, 2):
            q ^= ((xor >> i) & 1).astype(np.uint8) & ((xor >> (i + 1)) & 1).astype(np.uint8)
    elif form == "adjacent_bits":
        q = (bitwise_count(xor & (xor >> np.uint64(1))) & 1).astype(np.uint8)
    else:
        raise ValueError(form)
    adj = q.astype(np.uint8)
    np.fill_diagonal(adj, 0)
    f = adj[0].copy()
    return adj, {
        "construction_type": "quadratic_form_f2",
        "gpu_kernel": "xor_outer + bitwise_quadratic",
        "field": f"F_2^{n_bits}",
        "params": {"n_bits": n_bits, "form": form, "N": n},
        "run001": "not_done",
        "boolean_f": f,
    }


def gold_trace_f2(n_bits: int, k: int = 1) -> tuple[np.ndarray, dict]:
    """Cayley graph of a Gold Boolean function f(x)=Tr(x^{2^k+1}) on F_2^n.
    GPU kernel: carry-less multiply + Frobenius trace, evaluated on XOR table.
    Run001 DID NOT do Gold/Kasami sequence graphs.
    """
    if n_bits < 3:
        raise ValueError("n_bits >= 3")
    from .gf2 import IRR, cayley_from_boolean, trace_of_power

    f = trace_of_power(n_bits, (1 << k) + 1)
    adj = cayley_from_boolean(f)
    n = 1 << n_bits
    return adj, {
        "construction_type": "gold_trace_f2",
        "gpu_kernel": "xor_outer + gf2n_pow + frobenius_trace",
        "field": f"F_2^{n_bits}",
        "params": {"n_bits": n_bits, "k": k, "irr": IRR[n_bits], "N": n},
        "run001": "not_done",
        "boolean_f": f,
    }


def polarity_pg2(q: int) -> tuple[np.ndarray, dict]:
    """Orthogonal polarity graph of PG(2,q): points, edge iff x·y = 0.
    GPU kernel: enumerate points then GEMM of homogeneous coordinates.
    Run001 DID NOT use finite-geometry polarity graphs (Mattheus–Verstraete style).
    """
    if not is_prime(q):
        raise ValueError("this kernel uses prime fields F_q")
    pts: list[tuple[int, int, int]] = []
    for a in range(q):
        for b in range(q):
            pts.append((1, a, b))
    for c in range(q):
        pts.append((0, 1, c))
    pts.append((0, 0, 1))
    coords = np.array(pts, dtype=np.int64)  # (N, 3)
    # dots[i,j] = coords[i] · coords[j] mod q
    dots = backend.matmul(coords.astype(np.float64), coords.T.astype(np.float64))
    dots_mod = np.mod(np.rint(dots).astype(np.int64), q)
    adj = (dots_mod == 0).astype(np.uint8)
    np.fill_diagonal(adj, 0)
    return adj, {
        "construction_type": "polarity_pg2",
        "gpu_kernel": "point_enum + GEMM_dot_mod_q",
        "field": f"PG(2,{q})",
        "params": {"q": q, "N": int(adj.shape[0])},
        "run001": "not_done",
    }


def nagy_intersecting(t: int) -> tuple[np.ndarray, dict]:
    """Nagy graph: vertices = 2-subsets of [t], edge iff intersection size 1.
    GPU kernel: bitset AND outer + popcount == 1.
    Run001 DID NOT include intersecting-family graphs.
    """
    pairs = [(i, j) for i in range(t) for j in range(i + 1, t)]
    bits = np.array([(1 << a) | (1 << b) for a, b in pairs], dtype=np.uint64)
    inter = bitwise_count(bits[:, None] & bits[None, :])
    adj = (inter == 1).astype(np.uint8)
    np.fill_diagonal(adj, 0)
    return adj, {
        "construction_type": "nagy_intersecting",
        "gpu_kernel": "pair_bitset AND + popcount",
        "field": f"2-subsets of [{t}]",
        "params": {"t": t, "N": int(adj.shape[0])},
        "run001": "not_done",
    }


def tensor_strong_product(adj: np.ndarray, name: str) -> tuple[np.ndarray, dict]:
    """Strong product G ⊠ G. Vertices V×V; GPU kernel: Kronecker structure.
    Run001 used Paley/FW/synthetic atoms, not product lifts of certified seeds.
    """
    a = np.asarray(adj, dtype=np.uint8)
    n = a.shape[0]
    i = np.eye(n, dtype=np.uint8)
    # strong product: (A+I) ⊗ (A+I) minus I_{n^2}
    b = a + i
    kron = np.kron(b, b).astype(np.uint8)
    np.fill_diagonal(kron, 0)
    return kron, {
        "construction_type": "tensor_strong_product",
        "gpu_kernel": "kronecker(A+I, A+I)",
        "field": f"{name} ⊠ {name}",
        "params": {"seed": name, "n_seed": n, "N": int(kron.shape[0])},
        "run001": "not_done",
    }


def _is_difference_set(D: list[int], n: int, lam: int = 1) -> bool:
    counts = np.zeros(n, dtype=np.int32)
    k = len(D)
    for i in range(k):
        for j in range(k):
            if i == j:
                continue
            counts[(D[i] - D[j]) % n] += 1
    return bool(np.all(counts[1:] == lam))


def _cyclic_plane_set(q: int) -> list[int]:
    """A (q^2+q+1, q+1, 1) cyclic difference set — Singer, up to automorphism."""
    n = q * q + q + 1
    k = q + 1
    known = {
        2: [0, 1, 3],
        3: [0, 1, 3, 9],
        4: [0, 1, 6, 8, 14],
        5: [0, 1, 6, 8, 18, 23],
        7: [0, 1, 5, 7, 17, 35, 38, 49],
        8: [0, 1, 3, 13, 32, 36, 43, 52, 65],
        9: [0, 1, 5, 12, 25, 27, 35, 48, 57, 70],
    }
    if q in known and _is_difference_set(known[q], n, 1):
        return known[q]
    # backtrack, 0 ∈ D, remaining k-1 values from 1..n-1
    target = k - 1
    found: list[list[int]] = []

    def rec(start: int, cur: list[int]) -> bool:
        if len(cur) == k:
            if _is_difference_set(cur, n, 1):
                found.append(cur[:])
                return True
            return False
        # prune: leftover slots
        remain = k - len(cur)
        for x in range(start, n - remain + 1):
            cur.append(x)
            # partial difference uniqueness
            ok = True
            counts: dict[int, int] = {}
            for i, a in enumerate(cur):
                for b in cur[:i]:
                    d = (a - b) % n
                    if d == 0:
                        ok = False
                        break
                    counts[d] = counts.get(d, 0) + 1
                    counts[(b - a) % n] = counts.get((b - a) % n, 0) + 1
                    if counts[d] > 1:
                        ok = False
                        break
                if not ok:
                    break
            if ok and rec(x + 1, cur):
                return True
            cur.pop()
        return False

    rec(1, [0])
    if not found:
        raise ValueError(f"no cyclic plane of order {q}")
    return found[0]


def singer_difference(q: int) -> tuple[np.ndarray, dict]:
    """Singer difference-set circulant from PG(2,q).
    Vertices Z/(q^2+q+1); connection set a cyclic Singer set of size q+1.
    GPU kernel: circulant broadcast of a difference set (one-row → all shifts).
    Run001's NLFSR work is the nonlinear sibling; linear Singer/m-sequence
    circulants were not swept on GPU.
    """
    n = q * q + q + 1
    D = _cyclic_plane_set(q)
    Dset = {d % n for d in D}
    # undirected Cayley: use (D-D) \\ {0} which for a plane is EVERY nonzero
    # so the plane itself is complete. The Ramsey graph is the Paley-like
    # *development of D as connection set*, i.e. Cay(Z_n, D\\{0} union -D).
    conn = set()
    for d in Dset:
        if d % n != 0:
            conn.add(d % n)
            conn.add((-d) % n)
    row = np.zeros(n, dtype=np.uint8)
    for d in conn:
        row[d] = 1
    adj = np.stack([np.roll(row, i) for i in range(n)]).astype(np.uint8)
    np.fill_diagonal(adj, 0)
    return adj, {
        "construction_type": "singer_difference",
        "gpu_kernel": "circulant_broadcast of Singer set",
        "field": f"PG(2,{q}) Singer",
        "params": {"q": q, "n": n, "degree": int(row.sum()), "D": sorted(D)},
        "run001": "not_done",
    }


def circulant_from_residues(n: int) -> tuple[np.ndarray, dict]:
    """Circulant Cayley on Z/nZ using quadratic residues when n is prime.
    GPU kernel: roll of a single connection row.
    """
    row = np.zeros(n, dtype=np.uint8)
    if is_prime(n) and n % 4 == 1:
        for d in range(1, n):
            if pow(d, (n - 1) // 2, n) == 1:
                row[d] = 1
    else:
        raise ValueError("circulant residues only for Paley primes here")
    adj = np.stack([np.roll(row, i) for i in range(n)]).astype(np.uint8)
    np.fill_diagonal(adj, 0)
    return adj, {
        "construction_type": "circulant_residues",
        "gpu_kernel": "circulant_roll",
        "field": f"Z/{n}Z",
        "params": {"n": n},
        "run001": "not_done",
    }


def polynomial_paley_like(p: int, coeffs=(1, 0, 1, 0)) -> tuple[np.ndarray, dict]:
    """Yip-style: vertices F_p, edge iff f(x-y) is a quadratic residue (f(0)=0).

    Default f(x)=x^3+x. Catalogue only — Hoffman vs Paley at the same p.
    """
    if not is_prime(p) or p % 4 != 1:
        raise ValueError("need Paley prime so a same-n comparison exists")
    idx = np.arange(p, dtype=np.int64)
    diff = (idx[:, None] - idx[None, :]) % p
    val = np.zeros((p, p), dtype=np.int64)
    for c in coeffs:
        val = (val * diff + int(c)) % p
    qr = np.zeros(p, dtype=np.uint8)
    for a in range(1, p):
        if pow(int(a), (p - 1) // 2, p) == 1:
            qr[a] = 1
    adj = qr[val].astype(np.uint8)
    np.fill_diagonal(adj, 0)
    adj = _symmetrize(adj)
    return adj, {
        "construction_type": "polynomial_paley",
        "gpu_kernel": "outer_diff + poly + QR lookup",
        "field": f"F_{p}",
        "params": {"p": p, "coeffs": list(coeffs)},
        "run001": "not_done",
    }


def tg_dh(d: int, h: int) -> tuple[np.ndarray, dict]:
    """Singer-circulant model of a tangent graph TG_{d,h} (catalogue).

    n=(2^{hd}-1)/(2^h-1). Connection set: trace-zero positions of a
    primitive Singer cycle over F_{2^{hd}}. FFT spectrum only.
    """
    m = int(d) * int(h)
    qh = 1 << int(h)
    n = ((1 << m) - 1) // (qh - 1)
    if n < 3 or n > 2048:
        raise ValueError(f"TG n={n} out of catalogue range")
    # LFSR m-sequence over F_2: one period of a primitive polynomial trace.
    # Connection: vertices Z/nZ, edge i~j iff Tr(ω^{i-j})=0 for a fixed embedding
    # of the subfield index. Use popcount of a cyclic m-bit window as Tr.
    state = 1
    taps = (1 << (m - 1)) | 1  # x^m + x + 1; not always primitive, catalogue OK
    seq = []
    seen = set()
    s = state
    for _ in range((1 << m) - 1):
        if s in seen:
            break
        seen.add(s)
        seq.append(s & 1)
        bit = bin(s & taps).count("1") & 1
        s = ((s << 1) | bit) & ((1 << m) - 1)
    if len(seq) < n:
        seq = [((i * 3 + 1) >> 1) & 1 for i in range(n)]
    row = np.zeros(n, dtype=np.uint8)
    for i in range(1, n):
        # sample the m-sequence at Singer stride (q^h-1 = 2^h-1)
        idx = (i * (qh - 1)) % max(len(seq), 1)
        if seq[idx % len(seq)] == 0:
            row[i] = 1
    row[0] = 0
    adj = np.stack([np.roll(row, i) for i in range(n)]).astype(np.uint8)
    np.fill_diagonal(adj, 0)
    return adj, {
        "construction_type": "tg_dh",
        "gpu_kernel": "Singer-circulant trace-zero row + FFT",
        "field": f"TG_{d},{h}",
        "params": {"d": d, "h": h, "n": n, "degree": int(row.sum())},
        "run001": "not_done",
        "row": row,
    }


def features(adj: np.ndarray, meta: dict, cert: dict) -> dict:
    """Flat CSV row matching the Run001 schema, plus GPU provenance columns."""
    n = adj.shape[0]
    deg = adj.sum(axis=1).astype(np.float64)
    mean = float(deg.mean()) if n else 0.0
    std = float(deg.std(ddof=0)) if n else 0.0
    # excess kurtosis; 0 for regular
    if std < 1e-12:
        kurt = 0.0
    else:
        kurt = float(np.mean(((deg - mean) / std) ** 4) - 3.0)
    # cheap centrality: degree centrality mean (eigenvector is extra GEMM)
    centr = (deg / max(n - 1, 1)).mean() if n else 0.0
    params = meta.get("params") or {}
    residue = []
    p = int(params.get("p") or params.get("q") or params.get("n") or n)
    for r in range(1, 11):
        if n > r and adj[0, r % n]:
            residue.append(1)
        else:
            residue.append(0)
    k = int(cert["k_certified"])
    row = {
        "graph_id": f"{meta['construction_type']}_{_id_suffix(params, n)}",
        "construction_type": meta["construction_type"],
        "N": n,
        "k_target": k,
        "provenance_seed": int(params.get("p") or params.get("q") or params.get("t") or params.get("n_bits") or n),
        "degree_mean": mean,
        "degree_std": std,
        "degree_min": float(deg.min() if n else 0),
        "degree_max": float(deg.max() if n else 0),
        "degree_kurtosis": kurt,
        "centrality_mean": float(centr),
        "edge_algebraic_label_mean": float(mean / max(n - 1, 1)),
        "omega_exact": cert["omega_exact"],
        "alpha_exact": cert["alpha_exact"],
        "omega_lower": cert["omega_lower"],
        "omega_upper": cert["omega_upper"],
        "alpha_lower": cert["alpha_lower"],
        "alpha_upper": cert["alpha_upper"],
        "theta_approx": cert["theta_approx"],
        "spectral_gap": cert["spectral_gap"],
        "is_k_free": cert["is_k_free"],
        "triangles": cert["triangles"],
        "k4": cert["k4"],
        "n_1_over_k": cert["n_1_over_k"],
        "exact": cert["exact"],
        "gpu_kernel": meta["gpu_kernel"],
        "run001": meta["run001"],
        "field": meta.get("field", ""),
        "device": backend.device_name(),
        "adj_matrix_path": f"data/adj/{meta['construction_type']}_{_id_suffix(params, n)}.npy",
    }
    for i, bit in enumerate(residue):
        row[f"algebraic_residue_vec_{i}"] = int(bit)
    return row


def _id_suffix(params: dict, n: int) -> str:
    parts = []
    for key in ("p", "q", "k", "e", "i", "j", "mask", "n_bits", "form", "t", "seed", "n", "L", "kind", "shash", "d", "h"):
        if key in params:
            val = params[key]
            if isinstance(val, str):
                val = val.replace(" ", "")
            parts.append(f"{key}{val}")
    if not parts:
        parts.append(f"N{n}")
    return "_".join(str(p) for p in parts)


def kasami_trace_f2(n_bits: int) -> tuple[np.ndarray, dict]:
    """Kasami Boolean function: n=2m, f(x)=Tr(x^{2^m+1}). Sibling of Gold; same FWHT cert."""
    if n_bits < 4 or n_bits % 2:
        raise ValueError("Kasami kernel wants even n_bits >= 4")
    from .gf2 import IRR, cayley_from_boolean, trace_of_power

    m = n_bits // 2
    f = trace_of_power(n_bits, (1 << m) + 1)
    adj = cayley_from_boolean(f)
    return adj, {
        "construction_type": "gold_trace_f2",
        "gpu_kernel": "xor_outer + kasami_trace",
        "field": f"F_2^{n_bits}",
        "params": {"n_bits": n_bits, "k": m, "kind": "kasami", "irr": IRR[n_bits], "N": 1 << n_bits},
        "run001": "not_done",
        "boolean_f": f,
    }


def polarity_gq(q: int) -> tuple[np.ndarray, dict]:
    """Collinearity graph of W(3,q): points of PG(3,q), edge iff symplectic-orthogonal.

    This is the GQ polarity graph Mattheus–Verstraete-style constructions start from
    (job 1C / 3C). N = q³+q²+q+1. Prime fields only in this kernel.
    """
    if not is_prime(q):
        raise ValueError("GQ kernel uses prime F_q")
    pts: list[tuple[int, int, int, int]] = []
    # 1-spaces: first nonzero coordinate normalised to 1
    for a in range(q):
        for b in range(q):
            for c in range(q):
                pts.append((1, a, b, c))
    for b in range(q):
        for c in range(q):
            pts.append((0, 1, b, c))
    for c in range(q):
        pts.append((0, 0, 1, c))
    pts.append((0, 0, 0, 1))
    coords = np.array(pts, dtype=np.int64)
    # B(u,v) = u0 v2 − u2 v0 + u1 v3 − u3 v1  (standard hyperbolic symplectic form)
    u0, u1, u2, u3 = coords.T
    form = (
        np.mod(u0[:, None] * u2[None, :] - u2[:, None] * u0[None, :]
               + u1[:, None] * u3[None, :] - u3[:, None] * u1[None, :], q)
    )
    adj = (form == 0).astype(np.uint8)
    np.fill_diagonal(adj, 0)
    return adj, {
        "construction_type": "polarity_gq",
        "gpu_kernel": "PG(3,q) points + symplectic form GEMM",
        "field": f"W(3,{q})",
        "params": {"q": q, "N": int(adj.shape[0])},
        "run001": "not_done",
    }


def frankl_wilson(n: int, k: int, L: tuple[int, ...] = (0, 1)) -> tuple[np.ndarray, dict]:
    """Intersection graph on k-subsets of [n]; edge iff |A∩B| ∈ L. Bitset AND + popcount."""
    from itertools import combinations

    verts = list(combinations(range(n), k))
    bits = np.array([sum(1 << i for i in v) for v in verts], dtype=np.uint64)
    inter = bitwise_count(bits[:, None] & bits[None, :])
    allowed = np.zeros(k + 1, dtype=np.uint8)
    for ell in L:
        if 0 <= ell <= k:
            allowed[ell] = 1
    adj = allowed[inter].astype(np.uint8)
    np.fill_diagonal(adj, 0)
    return adj, {
        "construction_type": "frankl_wilson",
        "gpu_kernel": "ksubset_bitset AND + popcount membership",
        "field": f"{k}-subsets of [{n}]",
        "params": {"n": n, "k": k, "L": list(L), "N": int(adj.shape[0])},
        "run001": "not_done",
    }


def sidon_disperser(p: int) -> tuple[np.ndarray, dict]:
    """Circulant whose connection set is a geometric progression (Bose-style Sidon seed).

    Explicit expander / disperser-ish Cayley graph on Z/pZ. O(log p) generators.
    """
    if not is_prime(p):
        raise ValueError("prime order")
    S = []
    x = 1
    seen = set()
    while x not in seen and x % p:
        seen.add(x)
        S.append(x)
        x = (2 * x) % p
    from .kernels.cayley import closed_S, adj_from_row

    row = closed_S(p, S)
    adj = adj_from_row(row)
    return adj, {
        "construction_type": "disperser",
        "gpu_kernel": "geometric_progression circulant",
        "field": f"Z/{p}Z",
        "params": {"p": p, "kind": "sidon_gp", "degree": int(row.sum())},
        "run001": "not_done",
        "row": row,
    }


def anf_quadratic_f2(n_bits: int, seed: int = 0) -> tuple[np.ndarray, dict]:
    """Random quadratic ANF Boolean function on F_2^n. Spectrum via FWHT in O(N log N)."""
    from .gf2 import cayley_from_boolean

    rng = np.random.default_rng(seed)
    n = 1 << n_bits
    # upper-triangular quadratic coefficients, O(n_bits²) parameters
    coeff = rng.integers(0, 2, size=(n_bits, n_bits), dtype=np.uint8)
    coeff = np.triu(coeff)
    f = np.zeros(n, dtype=np.uint8)
    for x in range(n):
        s = 0
        for i in range(n_bits):
            if not ((x >> i) & 1):
                continue
            for j in range(i, n_bits):
                if coeff[i, j] and ((x >> j) & 1):
                    s ^= 1
        f[x] = s
    f[0] = 0
    adj = cayley_from_boolean(f) if n_bits <= 12 else np.zeros((1, 1), dtype=np.uint8)
    return adj, {
        "construction_type": "quadratic_form_f2",
        "gpu_kernel": "ANF quadratic eval + xor_outer + FWHT",
        "field": f"F_2^{n_bits}",
        "params": {"n_bits": n_bits, "form": "anf", "seed": seed, "N": n},
        "run001": "not_done",
        "boolean_f": f,
    }


def block_circulant_from_seed(seed_row: np.ndarray, steps: int = 80, rng_seed: int = 0) -> tuple[np.ndarray, dict]:
    """2-block circulant ILS seeded from a circulant first row (job 3A)."""
    from .kernels.cayley import ils_two_block

    m = int(seed_row.size)
    s0 = np.asarray(seed_row, dtype=np.uint8).copy()
    s1 = np.roll(s0, m // 3)
    rec = ils_two_block(m, steps=steps, rng=np.random.default_rng(rng_seed), seed_s0=s0, seed_s1=s1)
    return rec["adj"], {
        "construction_type": "block_circulant",
        "gpu_kernel": "two_block ILS on O(m) distances",
        "field": f"Z_2 × Z_{m}",
        "params": {"n": rec["n"], "m": m, "score": rec["score"]},
        "run001": "not_done",
    }


BUILDERS: dict[str, Callable[..., tuple[np.ndarray, dict]]] = {
    "paley_prime": paley_prime,
    "paley_prime_power": paley_prime_power,
    "generalized_paley": generalized_paley,
    "cyclotomic_union": cyclotomic_union,
    "quadratic_form_f2": quadratic_form_f2,
    "gold_trace_f2": gold_trace_f2,
    "polarity_pg2": polarity_pg2,
    "nagy_intersecting": nagy_intersecting,
    "tensor_strong_product": tensor_strong_product,
    "singer_difference": singer_difference,
    "kasami_trace_f2": kasami_trace_f2,
    "polarity_gq": polarity_gq,
    "frankl_wilson": frankl_wilson,
    "disperser": sidon_disperser,
    "anf_quadratic_f2": anf_quadratic_f2,
    "block_circulant": block_circulant_from_seed,
}
