"""What Run001 actually built versus GPU-native constructions it skipped.

This is the research answer, encoded so the dashboard and the CSV share one source.
"""

GAP = [
    {
        "id": "paley_prime",
        "name": "Paley of primes p ≡ 1 (mod 4)",
        "run001": "done",
        "gpu": True,
        "kernel": "outer_diff + Euler Legendre a^{(p-1)/2}",
        "why_gpu": "The full N×N difference tensor and batched modular exponentiation are one CUDA kernel.",
        "why_skipped_or_done": "Run001's 40% Paley slice: primes p ∈ [17, 997] only. This is the baseline, not a gap.",
        "family": "Cayley over F_p",
        "growth": "N = p ≈ k^2 (sub-exponential). Paley of order p has ω,α ~ √p.",
    },
    {
        "id": "paley_prime_power",
        "name": "Paley of prime powers F_{p^n}, n>1",
        "run001": "not_done",
        "gpu": True,
        "kernel": "batched F_{p^2} multiply-exponentiate on outer differences",
        "why_gpu": "Field arithmetic is a uniform (re, im) tensor; no Python-level per-edge loop.",
        "why_skipped_or_done": "Run001 spec: Paley restricted to primes p ∈ [17,997]. Prime-power Paley (q=9,25,49,121,169,289,…) was never generated.",
        "family": "Cayley over F_q",
        "growth": "Same Paley clique heuristic ω~√q, but denser parameter lattice than primes alone.",
    },
    {
        "id": "generalized_paley",
        "name": "Generalized Paley GP(p,k), k-th power residues, k>2",
        "run001": "not_done",
        "gpu": True,
        "kernel": "outer_diff + a^{(p-1)/k} == 1",
        "why_gpu": "Identical kernel to Paley with a different exponent; cubic/quartic/sextic families are free on GPU.",
        "why_skipped_or_done": "Run001 encoded algebraic residues as a 10-bit quadratic/cyclotomic sketch, but adjacency was quadratic Paley only. Cubic Paley (Clapham) and GP(p,4), GP(p,6) were not enumerated.",
        "family": "Cayley over F_p",
        "growth": "sparser than Paley (degree (p-1)/k). Used in the literature for R(7,7) and multicolour R_k(4).",
    },
    {
        "id": "cyclotomic_union",
        "name": "Cyclotomic class-union Cayley graphs",
        "run001": "not_done",
        "gpu": True,
        "kernel": "discrete-log table + class-membership mask on (x-y)",
        "why_gpu": "Once dlog[0..p) lives in device memory, every mask is a broadcast compare. Sweeping 2^{e/2} negation-closed subsets is embarrassingly parallel.",
        "why_skipped_or_done": "Task 4 asked to search cyclotomic classes guided by Random Forest importance. Artifacts show family-correlation CSVs, not a GPU mask sweep of index-e class unions.",
        "family": "Cayley over F_p",
        "growth": "Contains Paley (e=2) and GP as special cases; extra masks can beat Paley at the same p.",
    },
    {
        "id": "quadratic_form_f2",
        "name": "Quadratic-form Cayley graphs on F_2^n",
        "run001": "not_done",
        "gpu": True,
        "kernel": "XOR outer product + bitwise quadratic form",
        "why_gpu": "The most GPU-native kernel in the catalogue: N=2^n vertices, adjacency[i,j] = Q(i xor j). Maps to CUDA bitwise ops with no modular arithmetic.",
        "why_skipped_or_done": "Run001's algebraic graphs were Paley/Frankl–Wilson/NLFSR over odd-characteristic fields. Affine polar / symplectic quadrics over F_2 were absent.",
        "family": "Cayley over (F_2^n, XOR)",
        "growth": "Strongly regular for nondegenerate Q. N doubles with each bit; k grows much slower than log N.",
    },
    {
        "id": "gold_trace_f2",
        "name": "Gold / trace-of-power sequence graphs on F_2^n",
        "run001": "not_done",
        "gpu": True,
        "kernel": "XOR outer + GF(2^n) power + Frobenius trace",
        "why_gpu": "m-sequence / Gold / Kasami evaluation is a linear-feedback (or carry-less multiply) kernel. GPUs already do this for cryptography and CDMA.",
        "why_skipped_or_done": "NLFSR-Ramsey in Run001 used nonlinear feedback shift registers as an algebraic construction, almost certainly on CPU for tiny n. The linear Gold/Kasami siblings — which are the actual GPU bread-and-butter — were not batched.",
        "family": "Boolean-function Cayley",
        "growth": "Related to bent and almost-bent functions; clique size tied to the degree of the trace polynomial.",
    },
    {
        "id": "polarity_pg2",
        "name": "Orthogonal polarity graphs of PG(2,q)",
        "run001": "not_done",
        "gpu": True,
        "kernel": "point enumeration + GEMM of homogeneous coordinates (x·y ≡ 0)",
        "why_gpu": "Adjacency is a batched dot product — one cuBLAS GEMM plus a modulus compare. N = q^2+q+1.",
        "why_skipped_or_done": "Run001 stayed on diagonal Paley/FW hybrids. Polarity graphs of projective planes (and GQ polarity graphs used by Mattheus–Verstraete for R(4,t)) were not built.",
        "family": "Finite geometry",
        "growth": "Off-diagonal strength is the point: triangle structure is geometric, not random. GPU makes a q-sweep cheap.",
    },
    {
        "id": "nagy_intersecting",
        "name": "Nagy intersecting-family graphs",
        "run001": "not_done",
        "gpu": True,
        "kernel": "pair bitset AND outer + popcount == 1",
        "why_gpu": "Vertices are 2-subsets; intersection size is a bitwise popcount of an AND table — a textbook GPU reduction.",
        "why_skipped_or_done": "Classical explicit cubic construction R(t,t) > binom(t,2). Not in the 40/30/20/10 Paley/FW/synthetic/DIMACS mix.",
        "family": "Set systems",
        "growth": "N = t(t-1)/2 with ω,α ≤ t, so N ~ k^2/2 — same polynomial regime as Paley, fully explicit.",
    },
    {
        "id": "tensor_strong_product",
        "name": "Strong products / Kronecker lifts of certified seeds",
        "run001": "not_done",
        "gpu": True,
        "kernel": "kronecker(A+I, A+I)",
        "why_gpu": "Kronecker products are GPU BLAS. Lifting Paley(17)⊠Paley(17) is one call.",
        "why_skipped_or_done": "Run001 generated atoms, not recursive Abbott-style product families. No tensor/XOR/lexicographic lift appears in the listed CSVs.",
        "family": "Product lifts",
        "growth": "ω(G⊠G) ≤ (ω(G)+1)^2-style bounds; N squares. Explicit infinite family from any single seed.",
    },
    {
        "id": "singer_difference",
        "name": "Singer difference-set circulants (PG(2,q))",
        "run001": "not_done",
        "gpu": True,
        "kernel": "circulant broadcast of a (q^2+q+1, q+1, 1) difference set",
        "why_gpu": "A circulant is one row rolled N times — a gather kernel. Linear m-sequences generating Singer sets are LFSR steps, GPU-trivial.",
        "why_skipped_or_done": "Run001 explored NLFSR (nonlinear) algebraic graphs for Erdős 78. The linear Singer/m-sequence circulants that GPUs already generate as PN sequences were not certified as Ramsey graphs.",
        "family": "Circulant / design theory",
        "growth": "Degree q+1 on N=q^2+q+1 vertices; strongly regular (lattice of the projective plane).",
    },
    {
        "id": "block_circulant",
        "name": "Block-circulant / two-block Cayley search",
        "run001": "not_done",
        "gpu": True,
        "kernel": "batched circulant blocks + GPU local search / SAT",
        "why_gpu": "Exoo–McKay-style R(5,5) searches and the DSC-3 Galois cycle-type annealer are GPU iterated local search over connection sets.",
        "why_skipped_or_done": "Run001's RL task (PPO edge flips, GNN attention) was specified and then cut by the 100 GPU-hour budget. No gnn_model.pt appears in the Run001 artifact list. Block-circulant SAT for R(5,5) was never started.",
        "family": "Search on structured seeds",
        "growth": "Cell-wise (small Ramsey numbers), not an exponential diagonal family — but it is the GPU construction the compute budget was supposed to buy.",
        "implemented_here": False,
    },
    {
        "id": "ppo_gat",
        "name": "PPO edge-flip + GAT θ/K-free training",
        "run001": "not_done",
        "gpu": True,
        "kernel": "PyTorch Geometric GAT + PPO on adjacency Bernoulli actions",
        "why_gpu": "This is the named GPU workload of RamseyConstructor-GNN (Tasks 2–3).",
        "why_skipped_or_done": "Deliverables required gnn_model.pt. The listed Run001 files have RF/algebraic CSVs and Kosmos specs, not a trained GAT or PPO policy. Classification/regression targets (F1≥0.80, MSE≤1.0) were never reported from a GPU training run.",
        "family": "Learned search",
        "growth": "A search heuristic, not a parametric family. GPU-necessary, not GPU-sufficient — Berghaus–Wagner ICLR 2025 found RL can lose to random on R(4,4).",
        "implemented_here": False,
    },
    {
        "id": "lovasz_theta_gpu",
        "name": "GPU Lovász ϑ SDP (randomized / CVXPY)",
        "run001": "not_done",
        "gpu": True,
        "kernel": "SDP on GPU, or randomized sketch of the theta body",
        "why_gpu": "Task 5 Tier 3: ϑ(Ḡ) as an upper bound on ω(G), budgeted at 500 graphs on A100.",
        "why_skipped_or_done": "Budget reconciliation replaced ϑ with Hoffman/spectral proxies for all but a sampled 500. No verification_log.json / benchmark_log.json in the listed artifacts, so the GPU SDP subset likely did not ship.",
        "family": "Certification, not construction",
        "growth": "Does not build graphs; certifies them. GPU still unused relative to the spec.",
        "implemented_here": False,
    },
    {
        "id": "gemm_clique",
        "name": "GEMM clique counting (A³, neighborhood A³)",
        "run001": "not_done",
        "gpu": True,
        "kernel": "cuBLAS GEMM triangle/K4 counts",
        "why_gpu": "trace(A³)/6 and per-neighborhood K4 are pure matrix multiplies. Exact ω for N≤200 was assigned to CPU cliquer.",
        "why_skipped_or_done": "Tier 1 used cliquer on N≤200; Tier 2 MiniSat on ≤200 graphs; Tier 3 spectral proxies. Batched GEMM certification — the obvious GPU replacement for cliquer — was not used.",
        "family": "Certification",
        "growth": "Enables k-freeness checks on the GPU constructions above at N up to a few hundred.",
        "implemented_here": True,
    },
]

DONE_IN_RUN001 = [
    "Paley of primes p ≡ 1 (mod 4), p ∈ [17, 997]",
    "Frankl–Wilson hybrids (q, d) with edge unions against Paley",
    "Synthetic random-regular graphs with 1% algebraic edge flips",
    "A 10% public/DIMACS slice",
    "NLFSR algebraic graphs for Erdős 78 (CPU-scale n)",
    "Random Forest ω/α baseline and algebraic-feature correlations",
    "Hoffman / spectral-gap proxies in place of Lovász ϑ",
    "Flat CSV feature schema (degree stats, 10-bit residue vectors)",
]
